### ISSUE TITLE
Add support to upload secrets to Worker Vault

### ISSUE THREAD

**Issue by vinaypuppal** [detroitenglish/cloudflare-worker-webpack-plugin#1]
Hi,

Thankyou for this plugin. I found today that workers support secret vault, would it be possible to support this in this plugin?

### Cloudflare Worker Secrets Vault
Securely store and manage secret keys, tokens, and certificates for accessing protected resources inside of a Cloudflare Worker.

Docs: https://developers.cloudflare.com/workers/api/resource-bindings/secrets-vault/

**Comment by detroitenglish** [comment]
Nice idea 👍 I've added support for a metadata `json` file path to the configuration options in v1.3.0
